[project]
name = "tapo-c210-rtsp-viewer"
version = "0.1.0"
description = "Example scripts for viewing TP-Link Tapo C210 RTSP stream"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.8.0",
]

[tool.uv]
package = false
